services:
  web:
    build: .
    expose:
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=production
      - SESSION_SECRET=your-secret-key-change-in-production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./static:/app/static:ro
      - /etc/letsencrypt/live/uparking.ru/fullchain.pem:/etc/nginx/ssl/server.crt
      - /etc/letsencrypt/live/uparking.ru/privkey.pem:/etc/nginx/ssl/server.key
      - ./nginx.conf:/etc/nginx/nginx.conf
        #ports:
        #- "80:80"
        #- "443:443"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    driver_opts:
        com.docker.network.driver.mtu: 1450
