FROM nginx:alpine

# Копирование конфигурации nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Создание директории для статических файлов
RUN mkdir -p /app/static

# Удаление дефолтной конфигурации
RUN rm /etc/nginx/conf.d/default.conf

# Проверка конфигурации nginx
RUN nginx -t

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"] 